[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

upload_speed = 921600  
monitor_speed = 115200

# [수정] PlatformIO 전용 micro-ROS 라이브러리 사용
board_microros_distro = jazzy
board_microros_transport = serial  # 시리얼 통신 명시

lib_deps =
    https://github.com/rodneybakiskan/ps5-esp32.git
    https://github.com/micro-ROS/micro_ros_platformio.git

# [수정] platformio용은 복잡한 build_flags가 필요 없습니다.
# 라이브러리가 알아서 링크를 잡아줍니다.
board_build.partitions = huge_app.csv
