ekf_filter_node:
  ros__parameters:
    frequency: 100.0
    two_d_mode: true
    publish_tf: true
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom
    odom0: /wheel_twist_stamped
    odom0_config: [false, false, false, false, false, false, true, true, false, false, false, true, false, false, false]
    odom0_queue_size: 10
    imu0: /imu/data
    imu0_remove_gravitational_acceleration: true
    imu0_config: [false, false, false, false, false, true, false, false, false, true, true, true, true, true, true]
    imu0_relative: false
    imu0_queue_size: 10
    odom1: /odometry/gps
    odom1_config: [true, true, false, false, false, false, false, false, false, false, false, false, false, false, false]
    odom1_queue_size: 10
